# Use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.

#TLS context configuration

tls:
  keyPassword: "![e4kQX0QLXcj19lUEKWyziA==]"
  password: "![e4kQX0QLXcj19lUEKWyziA==]"
  
backendBearerToken:
  username: "![9APtkgS1muwgj9vK0rnNXQ==]"
  password: "![+ryWHi63/naf5E5JMOEY+w==]"
  grant_type: "![+ryWHi63/naf5E5JMOEY+w==]"