{
    "doNumber": "VALR230427611117",
    "doStatus": "Draft",
    "doType": "EXPORT",
    "billOfLading": "HAS06AW3",
    "booking": "123456",
    "originPort": "ITSLONGB",
    "destinationPort": "LBCTLONGB",
    "invoiceReferenceNumber": "F048099242",
    "customerCode": "KNVV",
    "customerName": "Kuehne + Nagel",
    "bcoName": "John Deere",
    "oceanCarrier": "Supra National",
    "voyage": "string",
    "vessel": "string",
    "standardCarrierAlphaCode": "SNEA-LAX",
    "comments": null,
    "shipments": [],
    "cargo": {
        "quantity": 5,
        "quantityUOM": "TL",
        "commodityGoodsNumber": "4611110",
        "freightDescription": "FAK",
        "commodityClass": "FAK",
        "commodityComments": "Test Comments11",
        "isHazmat": false,
        "grossWeight": 100.0,
        "grossWeightUOM": "KG",
        "tareWeight": 8400.0,
        "tareWeightUOM": "KGs",
        "netWeight": 150.0,
        "netWeightUOM": "LB",
        "grossVolume": 100.0,
        "grossVolumeUOM": "CM",
        "temperature": null,
        "temperatureUOM": null,
        "isShipmentOverweight": false,
        "packageType": "TOTAL_LOAD"
    },
    "container": {
        "number": "CTY10212",
        "equipmentSizeType": "40HC",
        "seal": "string",
        "isStackable": null,
        "isLoaded": "Y"
    },
    "stops": [
        {
            "id": 260,
            "doId": null,
            "stopType": "PICKUP",
            "stopNumber": 0,
            "locationName": "YUSEN TERMINAL",
            "locationId": null,
            "locationCode": null,
            "locationType": null,
            "locationAddress1": "701 NEWDOCK AVE.",
            "locationAddress2": null,
            "city": "Terminal Island",
            "state": "CA",
            "country": "United States",
            "postalCode": "90731"
        },
        {
            "id": 259,
            "doId": null,
            "stopType": "DELIVERY",
            "stopNumber": 1,
            "locationName": "Little Giant Ladder Systems, LLC",
            "locationId": null,
            "locationCode": null,
            "locationType": null,
            "locationAddress1": "1198 N Spring Creek Place",
            "locationAddress2": null,
            "city": "Springville",
            "state": "UT",
            "country": "United States",
            "postalCode": "84664"
        }
    ],
    "deliverySchedule": {
        "cutOffDate": "2023-04-30",
        "documentationCutOffDate": "2023-04-30",
        "lastFreeDate": "2023-05-05",
        "plannedPickup": "2023-05-05",
        "plannedVesselDeparture": "2023-04-29",
        "scheduledDeliveryDate": "2023-05-04",
        "returnDeliveryOrder": null,
        "bondedMove": null,
        "fumigationRequestedAt": null
    },
    "customAttributes": null,
    "doEvents": [],
    "deliveryOrderCustomerReferenceNumber": null
}